services:
  mysql:
    image: mariadb:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: tfs 
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_container
    environment:
      PMA_HOST: mysql
    ports:
      - "8080:80"